impl json object block && http_request block
ruijs/rui pull request #74
Opened 2024-08-02 08:14 UTC by slene

2024-08-02 12:36 UTC, imzshh requested changes

2024-08-02 12:36 UTC, imzshh commented on packages/blockly-extension/src/blocks/action_antdToast.ts
>        ["info", Level.Info],
toast的type可以默认为info

2024-08-02 12:36 UTC, imzshh commented on packages/blockly-extension/src/blocks/http_request.ts
> +  ["PATCH", "PATCH"],
把PATCH移到PUT下面

2024-08-12 02:11 UTC, slene commented on packages/blockly-extension/src/blocks/http_request.ts
> +    responseType: '${responseType}'
这么做的话，那就需要开发人员自己处理每个请求的错误结果

2024-08-12 03:31 UTC, imzshh approved these changes

2024-08-12 03:31 UTC, merged